"""initial game schema

Revision ID: f37b715409df
Revises: 
Create Date: 2026-10-03 22:42:51.121563

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'f37b715409df'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('LOBBY', 'ACTIVE', 'FINISHED', name='gamestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('claimed', sa.Boolean(), nullable=False),
    sa.Column('token', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'name', name='uq_game_team_name'),
    sa.UniqueConstraint('token')
    )
    op.create_table('game_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('money', sa.Integer(), nullable=False),
    sa.Column('fruit', sa.Integer(), nullable=False),
    sa.Column('trees', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('place', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'team_id', name='uq_game_result_team')
    )
    op.create_table('inventories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('money', sa.Integer(), nullable=False),
    sa.Column('fruit', sa.Integer(), nullable=False),
    sa.Column('seeds', sa.Integer(), nullable=False),
    sa.Column('poison', sa.Integer(), nullable=False),
    sa.Column('molotov', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id')
    )
    op.create_table('plots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attacker_team_id', sa.Integer(), nullable=False),
    sa.Column('target_plot_id', sa.Integer(), nullable=False),
    sa.Column('attack_type', sa.Enum('POISON', 'MOLOTOV', name='attacktype'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'FINISHED', 'STOPPED', name='attackstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['attacker_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['target_plot_id'], ['plots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plot_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plot_a_id', sa.Integer(), nullable=False),
    sa.Column('plot_b_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['plot_a_id'], ['plots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plot_b_id'], ['plots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plot_a_id', 'plot_b_id', name='uq_plot_connection')
    )
    op.create_table('trees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plot_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('HEALTHY', 'BURNING', 'DEAD', name='treestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plot_id'], ['plots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plot_id')
    )
    op.create_table('branches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tree_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('HEALTHY', 'POISONED', name='branchstatus'), nullable=False),
    sa.Column('fruit', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tree_id'], ['trees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('branches')
    op.drop_table('trees')
    op.drop_table('plot_connections')
    op.drop_table('attacks')
    op.drop_table('plots')
    op.drop_table('inventories')
    op.drop_table('game_results')
    op.drop_table('teams')
    op.drop_table('games')
    # ### end Alembic commands ###